-- ============================================================
-- Tableau Analytical Views
-- Auto-generated by 05_create_sql_views.py
-- Generated: 2026-07-24 05:41:34
-- ============================================================

-- vw_portfolio_performance
DROP VIEW IF EXISTS vw_portfolio_performance;
CREATE VIEW IF NOT EXISTS vw_portfolio_performance AS
        SELECT
            dp.trade_date,
            ph.ticker,
            ph.sector,
            cm.company_name,
            ph.shares_held,
            ph.buy_price,
            dp.close_price,
            dp.adj_close,
            dp.volume,
            cr.daily_return,
            cr.cumulative_return,
            (ph.shares_held * dp.adj_close) AS market_value,
            (ph.shares_held * ph.buy_price) AS cost_basis,
            (ph.shares_held * dp.adj_close) - (ph.shares_held * ph.buy_price) AS unrealized_pnl,
            CASE
                WHEN ph.buy_price > 0
                THEN ((dp.adj_close - ph.buy_price) / ph.buy_price) * 100
                ELSE 0
            END AS pnl_pct
        FROM daily_prices dp
        INNER JOIN portfolio_holdings ph ON dp.ticker = ph.ticker
        INNER JOIN computed_daily_returns cr ON dp.ticker = cr.ticker AND dp.trade_date = cr.trade_date
        LEFT JOIN company_metadata cm ON dp.ticker = cm.ticker
        ORDER BY dp.trade_date, ph.ticker;

-- vw_risk_dashboard
DROP VIEW IF EXISTS vw_risk_dashboard;
CREATE VIEW IF NOT EXISTS vw_risk_dashboard AS
        SELECT
            rm.ticker,
            COALESCE(cm.company_name, rm.ticker) AS display_name,
            rm.lookback_period,
            rm.as_of_date,
            MAX(CASE WHEN rm.metric_name = 'annualized_return' THEN rm.metric_value END) AS annualized_return,
            MAX(CASE WHEN rm.metric_name = 'annualized_volatility' THEN rm.metric_value END) AS annualized_volatility,
            MAX(CASE WHEN rm.metric_name = 'sharpe_ratio' THEN rm.metric_value END) AS sharpe_ratio,
            MAX(CASE WHEN rm.metric_name = 'sortino_ratio' THEN rm.metric_value END) AS sortino_ratio,
            MAX(CASE WHEN rm.metric_name = 'var_95' THEN rm.metric_value END) AS var_95,
            MAX(CASE WHEN rm.metric_name = 'cvar_95' THEN rm.metric_value END) AS cvar_95,
            MAX(CASE WHEN rm.metric_name = 'max_drawdown' THEN rm.metric_value END) AS max_drawdown,
            MAX(CASE WHEN rm.metric_name = 'beta' THEN rm.metric_value END) AS beta,
            MAX(CASE WHEN rm.metric_name = 'alpha' THEN rm.metric_value END) AS alpha,
            MAX(CASE WHEN rm.metric_name = 'tracking_error' THEN rm.metric_value END) AS tracking_error,
            MAX(CASE WHEN rm.metric_name = 'information_ratio' THEN rm.metric_value END) AS information_ratio,
            MAX(CASE WHEN rm.metric_name = 'skewness' THEN rm.metric_value END) AS skewness,
            MAX(CASE WHEN rm.metric_name = 'kurtosis' THEN rm.metric_value END) AS kurtosis,
            MAX(CASE WHEN rm.metric_name = 'total_return' THEN rm.metric_value END) AS total_return
        FROM computed_risk_metrics rm
        LEFT JOIN company_metadata cm ON rm.ticker = cm.ticker
        GROUP BY rm.ticker, rm.lookback_period, rm.as_of_date;

-- vw_sector_allocation
DROP VIEW IF EXISTS vw_sector_allocation;
CREATE VIEW IF NOT EXISTS vw_sector_allocation AS
        SELECT
            sa.sector,
            sa.total_market_value,
            sa.portfolio_weight,
            sa.sector_return,
            sa.as_of_date,
            COUNT(ph.ticker) AS num_stocks,
            GROUP_CONCAT(ph.ticker, ', ') AS tickers_in_sector
        FROM computed_sector_analysis sa
        LEFT JOIN portfolio_holdings ph ON sa.sector = ph.sector
        GROUP BY sa.sector, sa.total_market_value, sa.portfolio_weight,
                 sa.sector_return, sa.as_of_date
        ORDER BY sa.portfolio_weight DESC;

-- vw_benchmark_comparison
DROP VIEW IF EXISTS vw_benchmark_comparison;
CREATE VIEW IF NOT EXISTS vw_benchmark_comparison AS
        SELECT
            ps.trade_date,
            ps.total_portfolio_value,
            ps.daily_return AS portfolio_daily_return,
            ps.cumulative_return AS portfolio_cumulative_return,
            ps.drawdown AS portfolio_drawdown,
            bp.close_price AS benchmark_price,
            -- Benchmark cumulative return (normalized to first day)
            (bp.close_price / FIRST_VALUE(bp.close_price) OVER (ORDER BY ps.trade_date)) - 1
                AS benchmark_cumulative_return
        FROM computed_portfolio_summary ps
        LEFT JOIN benchmark_prices bp ON ps.trade_date = bp.trade_date
        WHERE bp.close_price IS NOT NULL
        ORDER BY ps.trade_date;

-- vw_stock_detail
DROP VIEW IF EXISTS vw_stock_detail;
CREATE VIEW IF NOT EXISTS vw_stock_detail AS
        SELECT
            dp.ticker,
            cm.company_name,
            ph.sector,
            ph.shares_held,
            ph.buy_price,
            ph.buy_date,
            dp.trade_date,
            dp.open_price,
            dp.high_price,
            dp.low_price,
            dp.close_price,
            dp.adj_close,
            dp.volume,
            cr.daily_return,
            cr.cumulative_return,
            (ph.shares_held * dp.adj_close) AS current_value,
            (ph.shares_held * ph.buy_price) AS invested_value,
            -- 7-day moving average
            AVG(dp.adj_close) OVER (
                PARTITION BY dp.ticker
                ORDER BY dp.trade_date
                ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
            ) AS ma_7d,
            -- 30-day moving average
            AVG(dp.adj_close) OVER (
                PARTITION BY dp.ticker
                ORDER BY dp.trade_date
                ROWS BETWEEN 29 PRECEDING AND CURRENT ROW
            ) AS ma_30d,
            -- 90-day moving average
            AVG(dp.adj_close) OVER (
                PARTITION BY dp.ticker
                ORDER BY dp.trade_date
                ROWS BETWEEN 89 PRECEDING AND CURRENT ROW
            ) AS ma_90d
        FROM daily_prices dp
        INNER JOIN portfolio_holdings ph ON dp.ticker = ph.ticker
        INNER JOIN computed_daily_returns cr ON dp.ticker = cr.ticker AND dp.trade_date = cr.trade_date
        LEFT JOIN company_metadata cm ON dp.ticker = cm.ticker
        ORDER BY dp.ticker, dp.trade_date;

-- vw_monthly_returns
DROP VIEW IF EXISTS vw_monthly_returns;
CREATE VIEW IF NOT EXISTS vw_monthly_returns AS
        SELECT
            SUBSTR(trade_date, 1, 4) AS year,
            CAST(SUBSTR(trade_date, 6, 2) AS INTEGER) AS month,
            CASE CAST(SUBSTR(trade_date, 6, 2) AS INTEGER)
                WHEN 1 THEN 'Jan' WHEN 2 THEN 'Feb' WHEN 3 THEN 'Mar'
                WHEN 4 THEN 'Apr' WHEN 5 THEN 'May' WHEN 6 THEN 'Jun'
                WHEN 7 THEN 'Jul' WHEN 8 THEN 'Aug' WHEN 9 THEN 'Sep'
                WHEN 10 THEN 'Oct' WHEN 11 THEN 'Nov' WHEN 12 THEN 'Dec'
            END AS month_name,
            -- Monthly return approximation using first and last day
            (last_close / first_close - 1) AS monthly_return
        FROM (
            SELECT
                SUBSTR(trade_date, 1, 7) AS year_month,
                trade_date,
                FIRST_VALUE(total_portfolio_value) OVER (
                    PARTITION BY SUBSTR(trade_date, 1, 7)
                    ORDER BY trade_date ASC
                ) AS first_close,
                LAST_VALUE(total_portfolio_value) OVER (
                    PARTITION BY SUBSTR(trade_date, 1, 7)
                    ORDER BY trade_date ASC
                    RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
                ) AS last_close
            FROM computed_portfolio_summary
        )
        GROUP BY SUBSTR(trade_date, 1, 7)
        ORDER BY year, month;

-- vw_correlation_matrix
DROP VIEW IF EXISTS vw_correlation_matrix;
CREATE VIEW IF NOT EXISTS vw_correlation_matrix AS
        SELECT
            cm1.ticker_1,
            cm1.ticker_2,
            cm1.correlation,
            cm1.lookback_period,
            COALESCE(meta1.sector, 'Unknown') AS sector_1,
            COALESCE(meta2.sector, 'Unknown') AS sector_2,
            CASE
                WHEN cm1.correlation >= 0.7 THEN 'High Positive'
                WHEN cm1.correlation >= 0.3 THEN 'Moderate Positive'
                WHEN cm1.correlation >= -0.3 THEN 'Low/No Correlation'
                WHEN cm1.correlation >= -0.7 THEN 'Moderate Negative'
                ELSE 'High Negative'
            END AS correlation_category
        FROM computed_correlation_matrix cm1
        LEFT JOIN company_metadata meta1 ON cm1.ticker_1 = meta1.ticker
        LEFT JOIN company_metadata meta2 ON cm1.ticker_2 = meta2.ticker;

-- vw_top_movers
DROP VIEW IF EXISTS vw_top_movers;
CREATE VIEW IF NOT EXISTS vw_top_movers AS
        SELECT
            rm.ticker,
            COALESCE(cm.company_name, rm.ticker) AS company_name,
            ph.sector,
            rm.metric_value AS total_return,
            CASE
                WHEN rm.metric_value > 0 THEN 'Gainer'
                ELSE 'Loser'
            END AS direction,
            RANK() OVER (ORDER BY rm.metric_value DESC) AS rank_best,
            RANK() OVER (ORDER BY rm.metric_value ASC) AS rank_worst
        FROM computed_risk_metrics rm
        LEFT JOIN company_metadata cm ON rm.ticker = cm.ticker
        LEFT JOIN portfolio_holdings ph ON rm.ticker = ph.ticker
        WHERE rm.metric_name = 'total_return'
          AND rm.lookback_period = 'ALL'
          AND rm.ticker != 'PORTFOLIO'
        ORDER BY rm.metric_value DESC;

